// D:\VICTOR SHOPIFY\CODIGOS\Essential\essential\app\routes\codform\styles\codform.styles.ts
const palette = {
  surface: "#ffffff",
  surfaceSubdued: "#f4f6f8",
  surfaceMuted: "#f9fafb",
  textPrimary: "#202223",
  textSecondary: "#6d7175",
  textSubtle: "#8c9196",
  accent: "#2c6ecb",
  accentAlt: "#7c3aed",
  accentGradient: "linear-gradient(135deg, #2c6ecb 0%, #7c3aed 100%)",
  border: "rgba(32, 34, 35, 0.08)",
  borderStrong: "rgba(32, 34, 35, 0.16)",
  success: "#10b981",
  warning: "#f59e0b",
  danger: "#ef4444",
  shadow: "0 20px 45px rgba(15, 23, 42, 0.15)",
};

export const codFormStyles = {
  page: {
    minHeight: "100vh",
    background: "linear-gradient(180deg, #f9fafb 0%, #eef2f6 100%)",
    padding: "32px 0 56px",
  },
  pageContent: {
    maxWidth: "1440px",
    margin: "0 auto",
    padding: "0 32px",
  },
  headerBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "24px",
    background: palette.surface,
    borderRadius: "20px",
    padding: "24px 28px",
    boxShadow: "0 18px 40px rgba(12, 34, 66, 0.08)",
    border: `1px solid ${palette.border}`,
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
  },
  headerIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "56px",
    height: "56px",
    borderRadius: "16px",
    background: palette.accentGradient,
    color: "#fff",
    fontSize: "26px",
    boxShadow: "0 12px 30px rgba(44, 110, 203, 0.35)",
  },
  headerTitleGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  headerTitle: {
    fontSize: "22px",
    fontWeight: 700,
    color: palette.textPrimary,
    letterSpacing: "-0.02em",
  },
  headerSubtitle: {
    fontSize: "14px",
    color: palette.textSecondary,
  },
  headerMeta: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "10px",
  },
  metaBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 12px",
    borderRadius: "999px",
    background: palette.surfaceSubdued,
    border: `1px solid ${palette.border}`,
    fontSize: "13px",
    color: palette.textSecondary,
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  headerButtonGhost: {
    padding: "10px 18px",
    borderRadius: "10px",
    border: `1px dashed ${palette.borderStrong}`,
    background: "transparent",
    color: palette.textSecondary,
    fontWeight: 500,
    fontSize: "14px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  headerButtonSecondary: {
    padding: "10px 18px",
    borderRadius: "10px",
    border: `1px solid ${palette.borderStrong}`,
    background: palette.surface,
    color: palette.textPrimary,
    fontWeight: 500,
    fontSize: "14px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  headerButtonPrimary: {
    padding: "10px 22px",
    borderRadius: "10px",
    border: "none",
    background: palette.accentGradient,
    color: "#fff",
    fontWeight: 600,
    fontSize: "14px",
    cursor: "pointer",
    boxShadow: "0 15px 30px rgba(44, 110, 203, 0.25)",
    transition: "transform 0.2s ease",
  },
  insightRow: {
    marginTop: "28px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "18px",
  },
  insightCard: {
    background: palette.surface,
    borderRadius: "18px",
    padding: "20px 24px",
    border: `1px solid ${palette.border}`,
    boxShadow: "0 16px 40px rgba(15, 23, 42, 0.08)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
  },
  insightLabel: {
    fontSize: "13px",
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
    color: palette.textSubtle,
  },
  insightValue: {
    fontSize: "22px",
    fontWeight: 700,
    color: palette.textPrimary,
  },
  insightContext: {
    fontSize: "13px",
    color: palette.textSecondary,
  },
  layoutGrid: {
    marginTop: "32px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 450px) minmax(0, 1fr)",
    gap: "28px",
    alignItems: "start",
  },
  configColumn: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "24px",
  },
  surfaceCard: {
    background: palette.surface,
    borderRadius: "24px",
    padding: "28px",
    border: `1px solid ${palette.border}`,
    boxShadow: palette.shadow,
  },
  designPanel: {
    maxHeight: "calc(100vh - 220px)",
    overflowY: "auto" as const,
    paddingRight: "6px",
  },
  mainTitle: {
    fontSize: "28px",
    fontWeight: 700,
    color: palette.textPrimary,
    marginBottom: "28px",
    letterSpacing: "-0.015em",
  },
  sectionTitle: {
    fontSize: "18px",
    fontWeight: 600,
    color: palette.textPrimary,
    marginBottom: "14px",
  },
  sectionPanel: {
    borderRadius: "16px",
    border: `1px solid ${palette.border}`,
    background: palette.surface,
    boxShadow: "0 14px 32px rgba(15, 23, 42, 0.06)",
    overflow: "hidden",
  },
  sectionPanelHeader: {
    width: "100%",
    background: palette.surface,
    border: "none",
    padding: "18px 22px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    cursor: "pointer",
  },
  sectionPanelHeaderContent: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    textAlign: "left" as const,
  },
  sectionPanelTitle: {
    fontSize: "16px",
    fontWeight: 600,
    color: palette.textPrimary,
    letterSpacing: "-0.01em",
  },
  sectionPanelDescription: {
    fontSize: "13px",
    color: palette.textSecondary,
  },
  sectionPanelBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 10px",
    borderRadius: "999px",
    background: palette.surfaceSubdued,
    color: palette.accent,
    fontSize: "12px",
    fontWeight: 600,
  },
  sectionPanelToggle: {
    fontSize: "18px",
    transition: "transform 0.2s ease",
    color: palette.textSecondary,
  },
  sectionPanelBody: {
    padding: "22px 24px 26px",
    background: palette.surfaceSubdued,
  },
  sectionPanelBodyHidden: {
    display: "none",
  },
  modeButtons: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginBottom: "18px",
  },
  modeButton: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    padding: "22px 18px",
    border: `1px solid ${palette.border}`,
    borderRadius: "14px",
    background: palette.surface,
    cursor: "pointer",
    transition: "all 0.3s ease",
    fontSize: "15px",
    fontWeight: 500,
    gap: "6px",
  },
  modeButtonActive: {
    borderColor: palette.accent,
    background: palette.accentGradient,
    color: "#fff",
    boxShadow: "0 16px 32px rgba(124, 58, 237, 0.25)",
  },
  modeIcon: {
    fontSize: "26px",
    marginBottom: "6px",
  },
  infoBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: "12px",
    padding: "16px",
    background: "#ecf2fe",
    border: `1px solid rgba(44,110,203,0.25)`,
    borderRadius: "12px",
    fontSize: "13px",
    color: "#1d4ed8",
    lineHeight: "1.5",
  },
  previewButton: {
    background: palette.accentGradient,
    color: "white",
    border: "none",
    padding: "12px 24px",
    borderRadius: "10px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "transform 0.2s ease",
  },
  countrySelect: {
    width: "100%",
    padding: "12px 16px",
    border: `1px solid ${palette.borderStrong}`,
    borderRadius: "10px",
    fontSize: "15px",
    marginBottom: "10px",
    outline: "none",
    transition: "border-color 0.3s ease",
  },
  customizationInfo: {
    background: palette.surfaceSubdued,
    borderRadius: "14px",
    padding: "20px",
    marginBottom: "20px",
  },
  blockInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "12px",
    fontSize: "14px",
  },
  formBlocks: {
    background: palette.surfaceSubdued,
    borderRadius: "14px",
    padding: "20px",
    marginBottom: "30px",
  },
  formBlockHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "15px",
    background: palette.accent,
    color: "white",
    borderRadius: "10px",
    marginBottom: "4px",
    fontWeight: 600,
  },
  formBlock: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 15px",
    background: palette.surface,
    border: `1px solid ${palette.border}`,
    marginBottom: "4px",
    transition: "all 0.2s ease",
  },
  blockControls: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  dragHandle: {
    cursor: "move",
    color: "#9ca3af",
    fontSize: "16px",
  },
  visibilityBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "16px",
    opacity: 0.65,
  },
  blockName: {
    fontSize: "14px",
    color: palette.textPrimary,
    fontWeight: 500,
  },
  blockActions: {
    display: "flex",
    gap: "8px",
  },
  actionBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "6px",
    borderRadius: "4px",
    transition: "background 0.2s ease",
    color: "#6b7280",
    fontSize: "12px",
  },
  addCustomButton: {
    width: "100%",
    padding: "15px",
    background: "#111827",
    color: "white",
    border: "none",
    borderRadius: "10px",
    fontWeight: 500,
    cursor: "pointer",
    marginTop: "10px",
  },
  styleSection: {
    background: palette.surfaceSubdued,
    borderRadius: "14px",
    padding: "22px",
    marginBottom: "30px",
  },
  styleHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  resetButton: {
    background: "none",
    border: `1px solid ${palette.borderStrong}`,
    padding: "8px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    color: palette.textSecondary,
  },
  styleRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "18px",
    marginBottom: "18px",
  },
  styleControl: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
  },
  colorInputWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  colorPreview: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    border: `1px solid ${palette.border}`,
    flexShrink: 0,
  },
  colorInput: {
    flex: 1,
    padding: "8px 12px",
    border: `1px solid ${palette.borderStrong}`,
    borderRadius: "8px",
    fontSize: "14px",
    outline: "none",
  },
  rangeControl: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  rangeSlider: {
    flex: 1,
    height: "6px",
    background: palette.surfaceSubdued,
    borderRadius: "3px",
    outline: "none",
    cursor: "pointer",
  },
  rangeValue: {
    fontSize: "14px",
    fontWeight: 500,
    color: palette.textPrimary,
    minWidth: "40px",
    textAlign: "right" as const,
  },
  styleWarning: {
    marginTop: "6px",
    padding: "12px",
    background: "#fef3c7",
    border: "1px solid #fbbf24",
    borderRadius: "8px",
    fontSize: "13px",
    color: "#92400e",
  },
  checkboxControls: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "12px",
  },
  checkboxControl: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
  },
  textInput: {
    padding: "10px 12px",
    border: `1px solid ${palette.borderStrong}`,
    borderRadius: "8px",
    fontSize: "14px",
    outline: "none",
    width: "100%",
  },
  previewPanel: {
    position: "sticky" as const,
    top: "120px",
    height: "fit-content",
  },
  previewContainer: {
    background: palette.surface,
    borderRadius: "24px",
    padding: "28px",
    minHeight: "640px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: `1px solid ${palette.border}`,
    boxShadow: palette.shadow,
  },
  previewTopBar: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "18px",
  },
  previewTitleGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "6px",
  },
  previewTitle: {
    fontSize: "18px",
    fontWeight: 600,
    color: palette.textPrimary,
  },
  previewSubtitle: {
    fontSize: "13px",
    color: palette.textSecondary,
  },
  previewBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 12px",
    borderRadius: "999px",
    background: palette.surfaceSubdued,
    color: palette.accent,
    fontSize: "12px",
    fontWeight: 600,
  },
  previewDeviceSwitch: {
    display: "inline-flex",
    background: palette.surfaceSubdued,
    padding: "4px",
    borderRadius: "999px",
    gap: "4px",
    border: `1px solid ${palette.border}`,
  },
  previewDeviceButton: {
    padding: "6px 12px",
    borderRadius: "999px",
    border: "none",
    background: "transparent",
    fontSize: "13px",
    fontWeight: 500,
    color: palette.textSecondary,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  previewDeviceButtonActive: {
    background: palette.surface,
    color: palette.textPrimary,
    boxShadow: "0 4px 12px rgba(15, 23, 42, 0.08)",
  },
  previewFrame: {
    width: "100%",
    background: palette.surface,
    borderRadius: "24px",
    border: `1px solid ${palette.border}`,
    boxShadow: "0 25px 60px rgba(15, 23, 42, 0.12)",
    overflow: "hidden",
  },
  previewFrameHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "20px 28px",
    borderBottom: `1px solid ${palette.border}`,
    background: palette.surface,
  },
  previewFrameBody: {
    padding: "26px 28px 32px",
    background: palette.surfaceSubdued,
  },
  previewProductSummary: {
    display: "flex",
    alignItems: "center",
    gap: "18px",
    marginBottom: "22px",
  },
  previewProductImage: {
    width: "64px",
    height: "64px",
    borderRadius: "18px",
    background: "rgba(124, 58, 237, 0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "30px",
    color: palette.accentAlt,
  },
  previewProductMeta: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
  },
  previewProductName: {
    fontSize: "16px",
    fontWeight: 600,
    color: palette.textPrimary,
  },
  previewProductPrice: {
    fontSize: "15px",
    color: palette.textSecondary,
  },
  previewPhoneFrame: {
    width: "320px",
    borderRadius: "36px",
    padding: "24px",
    background: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
    position: "relative" as const,
    boxShadow: "0 32px 70px rgba(15,23,42,0.45)",
    display: "flex",
    justifyContent: "center",
  },
  previewPhoneScreen: {
    width: "100%",
    borderRadius: "28px",
    background: "#ffffff",
    padding: "22px 20px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "18px",
    boxShadow: "inset 0 0 0 1px rgba(32,34,35,0.05)",
  },
  previewFloatingButton: {
    background: palette.accentGradient,
    color: "#fff",
    borderRadius: "999px",
    padding: "14px 22px",
    fontWeight: 600,
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    boxShadow: "0 14px 30px rgba(44,110,203,0.35)",
  },
  modalOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '20px'
  },
  formModal: {
    background: 'white',
    borderRadius: '16px',
    maxWidth: '500px',
    width: '100%',
    maxHeight: '90vh',
    overflowY: 'auto' as const
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '25px',
    borderBottom: '1px solid #e5e7eb'
  },
  closeButton: {
    background: 'none',
    border: 'none',
    fontSize: '32px',
    color: '#666',
    cursor: 'pointer',
    padding: 0,
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%'
  },
  modalContent: {
    padding: '25px'
  },
  formHeader: {
    marginBottom: '25px'
  },
  productDisplay: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
    padding: '20px',
    background: '#f8fafc',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    position: 'relative' as const
  },
  productBadge: {
    position: 'absolute' as const,
    top: '-8px',
    left: '-8px',
    background: '#1f2937',
    color: 'white',
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: '600'
  },
  productEmoji: {
    fontSize: '32px'
  },
  productInfo: {
    flex: 1
  },
  orderSummary: {
    background: '#f8fafc',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '25px'
  },
  summaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '12px',
    fontSize: '16px'
  },
  summaryRowTotal: {
    borderTop: '2px solid #e5e7eb',
    paddingTop: '12px',
    marginBottom: 0,
    fontWeight: '700',
    fontSize: '18px'
  },
  freeShipping: {
    color: '#10b981',
    fontWeight: '600'
  },
  shippingSection: {
    marginBottom: '25px'
  },
  shippingOption: {
    display: 'flex',
    alignItems: 'center',
    padding: '15px',
    border: '2px solid #e5e7eb',
    borderRadius: '8px',
    background: 'white'
  },
  formSection: {
    marginBottom: '25px'
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '20px'
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column' as const
  },
  formGroupFullWidth: {
    gridColumn: '1 / -1'
  },
  formLabel: {
    fontWeight: '500',
    color: '#374151',
    marginBottom: '8px',
    fontSize: '14px'
  },
  formInput: {
    padding: '12px 16px',
    border: '2px solid #e5e7eb',
    borderRadius: '8px',
    fontSize: '16px',
    transition: 'all 0.3s ease',
    outline: 'none'
  },
  checkboxGroup: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    marginBottom: '20px'
  },
  submitButton: {
    width: '100%',
    background: 'linear-gradient(135deg, #1f2937 0%, #111827 100%)',
    color: 'white',
    border: 'none',
    padding: '18px 24px',
    borderRadius: '12px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px'
  },
  buyNowButton: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: 'white',
    border: 'none',
    padding: '15px 30px',
    borderRadius: '8px',
    fontWeight: '600',
    cursor: 'pointer',
    marginTop: '20px'
  },
  previewPage: {
    background: 'white',
    borderRadius: '8px',
    padding: '40px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    textAlign: 'center' as const,
    maxWidth: '300px'
  }
};